#!/usr/bin/env python3
import sys

sys.path.insert(1, "/opt/pbs/lib/softwalltime")
import softwalltime_psql

class Finisher(softwalltime_psql.Predictor):
    runtime = 0

    def __init__(self):
        super().__init__()

    def run(self, jobid, owner, runtime):

        runtime = self.walltime2sec(runtime)

        self.connect()
        if not self.check_table(self.table_name):
            self.disconnect()
            return

        if self.check_job_exists(jobid):
            self.insert_finished_job(True, jobid, owner, runtime)
        else:
            self.insert_finished_job(False, jobid, owner, runtime)

        self.disconnect()

        return

if len(sys.argv) != 4:
    print("Three arguments are needed")
    exit(1)
        
saver = Finisher()
saver.run(sys.argv[1], sys.argv[2], sys.argv[3])
