#!/usr/bin/env python3
import sys

sys.path.insert(1, "/opt/pbs/lib/softwalltime")
import softwalltime_psql

class Finisher(softwalltime_psql.Predictor):
    runtime = 0

    def __init__(self):
        super().__init__()

    def run(self, jobid, owner, runtime, walltime):

        runtime = self.walltime2sec(runtime)
        walltime = self.walltime2sec(walltime)

        self.connect()
        if not self.check_table(self.table_name):
            self.disconnect()
            return

        if self.check_job_exists(jobid):
            self.insert_finished_job(True, jobid, owner, runtime, walltime)
        else:
            self.insert_finished_job(False, jobid, owner, runtime, walltime)

        self.disconnect()

        return

    def run_full(self, jobid, owner, jobname, queue,  nodes, nodect, ncpus, ngpus, mem, interactive, soft_walltime, walltime, runtime):

        soft_walltime = self.walltime2sec(soft_walltime)
        walltime = self.walltime2sec(walltime)
        runtime = self.walltime2sec(runtime)

        self.connect()
        if not self.check_table(self.table_name):
            self.disconnect()
            return

        if self.check_job_exists(jobid):
            self.insert_finished_job_full(True, jobid, owner, jobname, queue,  nodes, int(nodect), int(ncpus), int(ngpus), self.mem2kb(mem), interactive, soft_walltime, walltime, runtime)
        else:
            self.insert_finished_job_full(False, jobid, owner, jobname, queue,  nodes, int(nodect), int(ncpus), int(ngpus), self.mem2kb(mem), interactive, soft_walltime, walltime, runtime)

        self.disconnect()

        return

if len(sys.argv) != 5 and  len(sys.argv) != 14:
    print("Right number of arguments must be provided: %s" % str(sys.argv))
    exit(1)
        
saver = Finisher()

if len(sys.argv) == 5:
    saver.run(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])

if len(sys.argv) == 14:
    saver.run_full(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5], sys.argv[6], sys.argv[7], sys.argv[8], sys.argv[9], sys.argv[10], sys.argv[11], sys.argv[12], sys.argv[13])